export { default as PorterRoute} from "./porter.route"
export { default as ChiefPorterRoute} from "./chief-porter.route"
export { default as HallTutorRoute} from "./hall-tutor.route"
export { default as AuthRoute} from "./auth.route"
export { default as FacilityRoute} from "./facility.route"
export { default as KeyLogRoute} from "./key-log.route"
export { default as KeyRoute} from "./key.route"
export { default as ResidentRoute} from "./resident.route"
export { default as RoomRoute} from "./room.route"
export { default as VisitLogRoute} from "./visit-log.route"
export { default as VisitorRoute } from "./visitor.route"
export { default as PublicRoute} from "./public.route"